### PR TITLE
add dashobard for events projection

### PR DESCRIPTION
**Pull request by rccrdpccl**
adding basic dashboard for events projection

image

### CODE REVIEW

**Comment by osherdp** [comment]
any chance to show how it looks like? :sweat_smile:

**Comment by osherdp** [comment]
> oops, I've missed this.... Unfortunately this is not on stage now, @osherdp do you want to see it before merging or after ? I could potentially load the json in stage if you'd like to see it beforehand

Preferably before we merge it. I cannot understand what this change means and what the dashboard looks like just by reading the configuration :sweat_smile:

**Comment by rccrdpccl** [comment]
@osherdp updated description

**Review by osherdp — APPROVED** [review]

**Pull request merged**
